### ISSUE TITLE
App crashes when sos button is pressed while gps is off.

### ISSUE THREAD

**Issue by nikhilgeo** [sachuss/sosAlert#23]
Steps to reproduce:

1. Launch the app turn.
2. You will be asked to turn on the GPS. Turn on GPS
3. Now press SOS button. In my case the SMS was not sent. 
4. Now turn off GPS before the SMS is sent.

I guess the crash happens may be because app is trying to get the location and  GPS got turned off in between acquiring the location.

**Comment by nikhilgeo** [comment]
```
2021-07-26 22:00:14.009 30637-30637/? E/ntamadam.raksh: Unknown bits set in runtime_flags: 0x8000
2021-07-26 22:00:14.223 30637-30674/com.vedantamadam.raksha E/Perf: Fail to get file list com.vedantamadam.raksha
2021-07-26 22:00:14.223 30637-30674/com.vedantamadam.raksha E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2021-07-26 22:00:14.223 30637-30674/com.vedantamadam.raksha E/Perf: Fail to get file list com.vedantamadam.raksha
2021-07-26 22:00:14.223 30637-30674/com.vedantamadam.raksha E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
2021-07-26 22:00:46.471 30637-30637/com.vedantamadam.raksha E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.vedantamadam.raksha, PID: 30637
    java.lang.AbstractMethodError: abstract method "void android.location.LocationListener.onProviderDisabled(java.lang.String)"
        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:369)
        at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:279)
        at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:295)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```
